import "dotenv/config";
import express from "express";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";

async function startServer() {
  const app = express();
  const PORT = 3000;

  // Middleware to parse JSON bodies (with increased limit for potential image data)
  app.use(express.json({ limit: '50mb' }));

  // API routes FIRST
  app.get("/api/health", (req, res) => {
    res.json({ status: "ok", message: "Backend API is running!" });
  });

  app.post("/api/generate-image", async (req, res) => {
    try {
      const { 
        referenceImageBase64, 
        mimeType, 
        angleDescription, 
        userText, 
        style, 
        tone, 
        appetisingMode,
        apiKey: userApiKey
      } = req.body;

      const apiKey = userApiKey || process.env.GEMINI_API_KEY;
      if (!apiKey) {
        return res.status(500).json({ error: "Server missing API Key" });
      }

      const ai = new GoogleGenAI({ apiKey });

      const appetisingText = appetisingMode
        ? "Make it highly appetising, balanced exposure, richer midtones, realistic but appealing color grading, controlled highlights on sauces/oils, crisp textures without looking over-processed."
        : "";

      const prompt = `Create a photorealistic food photo of the same dish as the reference image. Preserve the dish identity, plating, and key ingredients. Enhance visual appeal with professional food styling and lighting.
Angle: ${angleDescription}
Additional instructions: ${userText}
Style: ${style}, ${tone} tones.
${appetisingText}`;

      const response = await ai.models.generateContent({
        model: 'gemini-3-pro-image-preview',
        contents: {
          parts: [
            {
              inlineData: {
                data: referenceImageBase64,
                mimeType: mimeType,
              },
            },
            {
              text: prompt,
            },
          ],
        },
        config: {
          imageConfig: {
            imageSize: "1K",
            aspectRatio: "1:1",
          }
        }
      });

      const parts = response.candidates?.[0]?.content?.parts || [];
      
      for (const part of parts) {
        if (part.inlineData) {
          const imageUrl = `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
          return res.json({ url: imageUrl });
        }
      }

      // If we got here, no image was returned. Let's see if there's text (like a refusal).
      for (const part of parts) {
        if (part.text) {
          return res.status(400).json({ error: `Model returned text instead of an image: ${part.text}` });
        }
      }
      
      return res.status(500).json({ error: "No image generated by the model." });

    } catch (error: any) {
      console.error("Generation error:", error);
      res.status(500).json({ error: error.message || "Failed to generate image" });
    }
  });

  // Example custom API endpoint for the project
  app.post("/api/custom-action", (req, res) => {
    const { data } = req.body;
    // You can process data here (e.g., save to a database)
    res.json({ 
      success: true, 
      message: "Successfully called the project's own API!", 
      receivedData: data 
    });
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    app.use(express.static('dist'));
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
