import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

export async function generateFoodImage(
  referenceImageBase64: string,
  mimeType: string,
  angleDescription: string,
  userText: string,
  style: string,
  tone: string,
  appetisingMode: boolean
): Promise<string> {
  const appetisingText = appetisingMode
    ? "Make it highly appetising, balanced exposure, richer midtones, realistic but appealing color grading, controlled highlights on sauces/oils, crisp textures without looking over-processed."
    : "";

  const prompt = `Create a photorealistic food photo of the same dish as the reference image. Preserve the dish identity, plating, and key ingredients. Enhance visual appeal with professional food styling and lighting.
Angle: ${angleDescription}
Additional instructions: ${userText}
Style: ${style}, ${tone} tones.
${appetisingText}`;

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            data: referenceImageBase64,
            mimeType: mimeType,
          },
        },
        {
          text: prompt,
        },
      ],
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
    }
  }
  
  throw new Error("No image generated by the model.");
}
